### ISSUE TITLE
How can I use HTTPS?

### ISSUE THREAD

**Issue by YanChernikov** [scrollback/scrollback#547]
I'm trying to use Scrollback with HTTPS, however when I use https:// for the URL, this results in Firefox giving me a "Secure Connection Failed" error message. I've set the protocol to be "https:" in the client-config.js file, however this doesn't appear to help.

**Comment by aravindet** [comment]
Please see the http block on server-config.sample and
server-config-defaults, then add the http.https block in server-config.js
with your key and crt files.

**Comment by YanChernikov** [comment]
Thank you for the response. What are the key and crt paths relative to? I can't seem to use absolute paths, and when I try to use relative I get "Error: ENOENT, no such file or directory" with "undefined" in the path occasionally.

**Comment by YanChernikov** [comment]
I did some more investigating, and it turns out that if the path is valid (the files indeed to exist at the specified path), it prints:

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '[path]/scrollback-master/http/../undefined'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.init ([path]/scrollback-master/http/express.js:75:13)
    at init ([path]/scrollback-master/http/http.js:28:16)
    at module.exports ([path]/scrollback-master/http/http.js:45:3)
    at start ([path]/scrollback-master/index.js:41:2)
    at Object.<anonymous> ([path]/scrollback-master/index.js:47:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

where [path] is the path to scrollback-master. If the paths specified under key and crt are invalid, it will print the path instead of "undefined".

**Comment by aravindet** [comment]
@YanChernikov They should be relative to scrollback-master. Absolute paths should also work, so do try that.

One more thing, try having scrollback-master as your working directory while starting scrollback with node-index.

If any of these work please let us know, it still indicates a bug we have to fix. If they don't work, please print your server-config.js. (just the http section)
