### ISSUE TITLE
Can you share an installation document,I was in the Ubuntu14.04 installation failure.

### ISSUE THREAD

**Issue by hlj2722** [scrollback/scrollback#959]

**Comment by hlj2722** [comment]
info: 15-10-26T10:28:18 index.js:61:6 (13) Starting http
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
warn: 15-10-26T10:28:18 page.js:38:7 (63) Insecure connection. Specify https options in your config file.
New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
    at cb_nextTick (/srv/scrollback/node_modules/newrelic/lib/agent.js:164:16)
    at process._tickDomainCallback (node.js:492:13)
    at process.wrappedFunction (/srv/scrollback/node_modules/newrelic/lib/transaction/tracer/index.js:271:51)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at Server.wrappedListen2 [as _listen2] (/srv/scrollback/node_modules/newrelic/lib/instrumentation/core/net.js:16:46)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Object.init (/srv/scrollback/http/express.js:93:6)
    at init (/srv/scrollback/http/http.js:27:17)
    at module.exports (/srv/scrollback/http/http.js:40:2)
    at start (/srv/scrollback/index.js:63:2)
    at Object.<anonymous> (/srv/scrollback/index.js:72:1)
